name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  cd:
    uses: Re-Input/reinput-shared-workflows/.github/workflows/reusable-cd.yml@main
    with:
      image-name: reinput/discovery-server
      container-name: discovery-server
      container-port: "8761"
      network-type: "private"